version: "3.9"

services:
  # Local dev + Docker dev
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: domenico-backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    ports:
      - "3003:3000"  # Docker container port mapped to host
    volumes:
      - .:/app:cached   # for hot reload inside container
    depends_on:
      - redis
    restart: always

  # Redis service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always