name: Production CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/domenico-backend:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/domenico-backend:latest

      # Deploy to server
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}  # Add the server's IP address or hostname
          username: ${{ secrets.SERVER_USER }}  # Add the server's SSH username
          key: ${{ secrets.SERVER_SSH_KEY }}  # Add the private SSH key from GitHub Secrets
          script: |
            # Set up SSH key and known hosts for the connection
            mkdir -p ~/.ssh
            echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

            # Navigate to the app directory and pull & update Docker containers
            cd ~/app
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d